const ArrayProducts = [
    {
        id: 1,
        image: "/images/image1.png",
        title: "Elica 60 cm 1200 m3/hr Filterless Autoclean Kitchen Chimney with 15 Years Warranty (WDFL 606 HAC LT...",
        brand: "Samsung",
        category: "electronics",
        sales:300,
        rating: 4.0,
        reviews: 13204,
        currentPrice: 18990,
        salePrice: 12990,
        discount: 48,
        deliveryDate: "Sat, 14 Sept",
        deliveryTime: "7:00am - 9:00am",
    },

    {
        id: 2,
        image: "/images/image2.png",
        title:
        "Godrej 1.5 Ton 3 Star, 5-In-1 Convertible, Inverter Split AC (5 Years warranty, Copper, I-Sense Technology, 2023...",
        brand: "Godrej",
        sales:100,
        category: "electronics",
        rating: 4.0,
        reviews: 610,
        currentPrice: 18990,
        salePrice: 12990,
        discount: 48,
        deliveryDate: "Sat, 14 Sept",
        deliveryTime: "7:00am - 9:00am",
    },
    {
        id: 3,
        image: "/images/image3.png",
        title: "LG 28 L Convection Microwave Oven (MC2846BV, Black, Quartz Heater)",
        brand: "LG",
        sales:600,
        category: "electronics",
        rating: 4.0,
        reviews: 922,
        currentPrice: 18990,
        salePrice: 12990,
        discount: 48,
        deliveryDate: "Sat, 14 Sept",
        deliveryTime: "7:00am - 9:00am",
    },
    {
        id: 4,
        image: "/images/image4.png",
        title:
        "Samsung 8 kg, 5 star, Eco Bubble Tech, Digital Inverter Motor, Soft Closing Door, Fully-Automatic Top Load...",
        brand: "Samsung",
        sales:1000,
        category: "electronics",
        rating: 4.0,
        reviews: 25405,
        currentPrice: 18990,
        salePrice: 12990,
        discount: 48,
        deliveryDate: "Sat, 14 Sept",
        deliveryTime: "7:00am - 9:00am",
    },
    {
        id: 5,
        image: "/images/image5.png",
        title:
        "Samsung 7 kg, Eco Bubble Techn, Digital Inverter Motor, Soft Closing Door, Fully-Automatic Top Load Washing...",
        brand: "Samsung",
        sales:1000,
        category: "electronics",
        rating: 4.0,
        reviews: 6483,
        currentPrice: 18990,
        salePrice: 12990,
        discount: 48,
        deliveryDate: "Sat, 14 Sept",
        deliveryTime: "7:00am - 9:00am",
    },
    {
        id: 6,
        image: "/images/image6.png",
        title: "Samsung 7 kg, 3 star, Fully-Automatic Top Load Washing Machine (WA70A4002GS/TL, Imperial Silver)",
        brand: "Samsung",
        category: "electronics",
        sales:1000,
        rating: 4.0,
        reviews: 5173,
        currentPrice: 18990,
        salePrice: 12990,
        discount: 48,
        deliveryDate: "Sat, 14 Sept",
        deliveryTime: "7:00am - 9:00am",
    },
    {
        id: 7,
        image: "/images/image7.png",
        title:
        "LG 6.5 Kg 5 Star Inverter Turbodrum Fully Automatic Top Loading Washing Machine (T65SKSF4Z, 3 Smart Motion...",
        brand: "LG",
        category: "electronics",
        sales:900,
        rating: 4.0,
        reviews: 9922,
        currentPrice: 18990,
        salePrice: 12990,
        discount: 48,
        deliveryDate: "Sat, 14 Sept",
        deliveryTime: "7:00am - 9:00am",
    },
    {
        id: 8,
        image: "/images/image8.png",
        title:
        "Godrej 6.5 Kg 5 Star I-Wash Technology for Automatic One Touch Wash Fully-Automatic Top Load Washing Machine...",
        brand: "Godrej",
        category: "electronics",
        sales:800,
        rating: 4.0,
        reviews: 1440,
        currentPrice: 18990,
        salePrice: 12990,
        discount: 48,
        deliveryDate: "Sat, 14 Sept",
        deliveryTime: "7:00am - 9:00am",
    },
    {
        id: 9,
        image: "/images/image9.png",
        title:
        "Panasonic 20 L Solo Microwave Oven (NN-SM25JBFDG,Black)",
        brand: "Panasonic",
        category: "electronics",
        sales:300,
        rating: 4.0,
        reviews: 1440,
        currentPrice: 18990,
        salePrice: 12990,
        discount: 48,
        deliveryDate: "Sat, 14 Sept",
        deliveryTime: "7:00am - 9:00am",
    },
    {
        id: 10,
        image: "/images/image10.png",
        title:
        "Samsung 183 L, 4 Star, Digital Inverter, Direct-Cool Single Door Refrigerator (RR20C1824CR/HL, Red,",
        brand: "Samsung",
        category: "electronics",
        sales:100,
        rating: 4.0,
        reviews: 1440,
        currentPrice: 18990,
        salePrice: 12990,
        discount: 48,
        deliveryDate: "Sat, 14 Sept",
        deliveryTime: "7:00am - 9:00am",
    },
    {
        id: 11,
        image: "/images/image11.png",
        title:
        "LG 7 Kg, 5 Star, Direct Drive Technology, Steam Wash, 6 Motion DD, Smart Diagnosis, Fully-Automatic Front Load",
        brand: "LG",
        category: "electronics",
        sales:600,
        rating: 4.0,
        reviews: 1440,
        currentPrice: 18990,
        salePrice: 12990,
        discount: 48,
        deliveryDate: "Sat, 14 Sept",
        deliveryTime: "7:00am - 9:00am",
    },
    {
        id: 12,
        image: "/images/image12.png",
        title:
        "Whirlpool 184 L 2 Star Direct-Cool Single Door Refrigerator (205 WDE CLS 2S SAPPHIRE BLUE-Z, Blue,2023 Model)",
        brand: "Whirlpool",
        category: "electronics",
        sales:1000,
        rating: 4.0,
        reviews: 1440,
        currentPrice: 18990,
        salePrice: 12990,
        discount: 48,
        deliveryDate: "Sat, 14 Sept",
        deliveryTime: "7:00am - 9:00am",
    },
]

export default ArrayProducts;